name: Cindertalk
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60579
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Cindertalk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F2F4F2'
    - '#C6CFD1'
    - '#4C5B6D'
    - '#2F3A4B'
    - '#A2ADB4'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
